apps:
  - name: "1Password"
    type: System
    location: App Store
    notes: "Get QR code from other machine."
  - name: "Keybase"
    type: System
    location: https://keybase.io/download
    notes: "Activate from other machine."
  - name: "Dropbox"
    type: System
  - name: "Moom"
    type: System
    location: App Store
    notes: "Import config from this repo."
  - name: "The Clock"
    type: System
    location: App Store
    notes: "Import config from this repo."
  - name: "Menubar Stats"
    type: System
    location: App Store

  - name: "Brew"
    type: Dev
    location: https://brew.sh
  - name: "Xcode"
    type: Dev
    location: App Store
  - name: "iTerm"
    type: Dev
    notes: "Import config from this repo."
  - name: "VScode"
    type: Dev
  - name: "WebStorm"
    type: Dev
  - name: "GitKraken"
    type: Dev
  - name: "Figma"
    type: Dev
  - name: "Warp"
    type: Dev

  - name: "Signal"
    type: Comms
  - name: "Discord"
    type: Comms
  - name: "Zoom"
    type: Comms
  - name: "Skype"
    type: Comms
  - name: "WhatsApp"
    type: Comms
    location: App Store
  - name: "Telegram"
    type: Comms
    locations: App Store

  - name: "Google Chrome"
    type: App
    notes: "Set default in Settings."
  - name: "Microsoft Office"
    type: App
    notes: "DO NOT INSTALL FROM APP STORE"
    location: "https://account.microsoft.com/services"
  - name: "Affinity Designer"
    type: App
    location: App Store
  - name: "Affinity Photo"
    type: App
    location: App Store
  - name: "Affinity Publisher"
    type: App
    location: App Store
  - name: "Notion"
    type: App
    location: https://www.notionwizard.com/download-notion
  - name: "Sketch-up"
    type: App
    location: https://help.sketchup.com/en/downloading-sketchup
